package com.auctionuet.protocol.enums;

public enum Permission {
    MANAGE_USERS,
    GET_ALL_USERS,
    DELETE_USER,
    UPDATE_ROLE,
    VIEW_AUCTION,
    VIEW_BID_HISTORY,
    GET_PROFILE,
    UPDATE_PROFILE,
    PLACE_BID,
    SUBSCRIBE,
    UNSUBSCRIBE,
    CREATE_ITEM,
    UPDATE_ITEM,
    DELETE_ITEM,
    GET_MY_ITEMS,
    GET_ITEM_AUCTION_HISTORY,
    CREATE_AUCTION,
    START_AUCTION,
    DEPOSIT,
    WITHDRAW,
    GET_WALLET,
    GET_MY_TRANSACTIONS,
    PAY_AUCTION,
    GET_MY_PENDING_PAYMENTS,
    SET_AUTO_BID,
    CANCEL_AUTO_BID

}
